### PR TITLE
Make slate-editor compatible with latest slate

### LINKED ISSUE #43: Compatibility with latest Slate (currently 0.25.3)
The latest `slate-editor` is not compatible with the latest `slate` (0.25.3 at this time). Let's change that. I might be able to look into it myself but would welcome others be able to do it, too. I wanted to have this issue here so it could be tracked.

The first error I see is on this line:
 `exports.default = _slate.Raw.deserialize(initialEditorState, { terse: true });` in `initialEditorState.js`

.....the error is `Uncaught TypeError: Cannot read property 'deserialize' of undefined` so it must mean `Raw` is no longer an object in slate.

### PR DESCRIPTION
**Pull request by abobwhite**
Fixes #43

### CODE REVIEW

**Comment by abobwhite** [comment]
NOTE: I've listed in my commit comment, but this will be a breaking change due to the onChange callback now using a `Change` object vs `State`

Also - I think way back when I did my first PR I screwed up my branch so that's why there are 15 commits shown instead of one. If anyone cares, please let me know how I can fix it. Otherwise, I'll start fresh for any future PRs.

**Comment by gabrielrtakeda** [comment]
Excelent @abobwhite!
I am going to review your PR today!
And, many many thanks for the contribution!! 🎉 🎉 
We simply love when have contributions! ❤️

**Comment by gabrielrtakeda** [comment]
@abobwhite just one thing... Checking the commits list, I noticed that you have merged master into your branch... Instead of merging master branch into yours, you should have fetched the **nossas** repository branch master into your forked repository branch master and, created a new branch based on your fetched master...

**Comment by abobwhite** [comment]
Thanks @gabrielrtakeda. Is there anything I can easily change now with the commits/branching? Before contributing to this repo I'd never forked anything with the intent to create a PR before so I've been a little unsure how to keep my fork properly up-to-date with this main repo.

**Comment by gabrielrtakeda** [comment]
@abobwhite, one thing that you can do to solve this is, pulling the changes from nossas/master to abobwhite/master... You can follow the steps below:

## Fixing your master branch

1. `git remote add upstream git@github.com:nossas/slate-editor.git`
Adding the nossas repository (aliased as **upstream**) to your local tracking remote repos..

1. `git remote remove origin`
Removing the tracking remote repo aliased as **origin**.. (just for sure)

1. `git remote add origin git@github.com:abobwhite/slate-editor.git`
Adding your forked repository (aliased as **origin**) to your local tracking remote repos..

1. `git fetch --all`
Fetching all the remote repos code

1. `git checkout upgrade-slate`
Checking out to this PR branch, just temporarily..

1. `git branch -D master`
Deleting your current local master branch..

1. `git checkout upstream/master`
Checking out master branch of **nossas** repository..

1. `git checkout -b master`
Creating a new local master branch..

1. `git branch --set-upstream-to=origin/master`
Setting your local master branch to track your fork repo master branch..

1. `git push origin master -f`
Forcing push your up-to-date local master branch to your remote forked repo..

Now, your abobwhite/master branch is up-to-date with nossas/master branch...
Let's fix this PR branch...

## Fixing your PR branch

Assuming that the hole change of this PR is grouped into a single commit (2db800fe1d1c35bd23adb66e36172b0dca18ec05), we will only be cherry picking that commit and bringing to your now, up-to-date master branch... Just following the steps below:

1. `git checkout upgrade-slate`
Checking out to this PR branch..

1. `git log`
  Opening the list of commits, copy the hash of commit that we want... The hash will be something like in the screenshot below: screen shot 2017-10-05 at 15 12 28

1. `git branch -m upgrade-slate-backup`
Renaming current branch..

1. `git checkout master`
Checking out to master branch...

1. `git checkout -b upgrade-slate`
Creating a branch based on master with this PR branch name..

1. `git cherry-pick 2db800fe1d1c35bd23adb66e36172b0dca18ec05`
Cherry picking the commit that we have copied before..

1. `git push origin upgrade-slate -f`
Forcing push to abobwhite/upgrade-slate branch up-to-date to nossas/master branch and cherry picked commit...

## How to easily have abobwhite/master branch up-to-date with nossas/master branch

All the time that you will open a PR or, starting a new branch, just pulling out your master branch with nossas/master branch... You can do this following the next steps:

1. `git checkout master`
This master branch, needs to be pointing to your forked repo... You can check this running `git branch -vv`.. It should list all your branches and the remote tracking like `master 9d99385 [origin/master: ahead 1]`.. The `origin/master` is the track that we want...

1. `git pull upstream master`
The `upstream` alias is pointing to the **nossas** repo. So, we pulls out the nossas/master branch changes to your master branch...

**Comment by abobwhite** [comment]
@gabrielrtakeda Thanks for the tips! The PR now is just the 1 commit :) I think I was on track after my initial screw-up a month ago or so but the damage had already been done. I should be good now. 

Let me know if there are any PR issues - I'd like to start integrating this into my app asap. I might have to work from a local copy in the meantime.

**Comment by abobwhite** [comment]
@gabrielrtakeda I'm on Google Hangouts if you have any questions about the PR I can answer in real-time. I have it open all day and I have it on my phone as well. Thanks!

**Comment by abobwhite** [comment]
@gabrielrtakeda @igr-santos 

Any progress on this PR?

**Comment by abobwhite** [comment]
@gabrielrtakeda I will be forced to publish my fork to npm under a new name if we can't get this merged. I have an application for work that is blocked until I can merge this new version in. I'd prefer to not go that route and to keep development efforts consolidated in this repo that you maintain.

If it's a matter of bandwidth, I'd be happy to help be a maintainer for this repo so I can do these things myself, review PRs, etc.

**Comment by lpirola** [comment]
@abobwhite I'm sure it's not necessary to create a fork in npm, I'm testing your changes in our applications and soon we release a new version.

You can temporarily point directly to your branch and repository at packages.json, as told by npm doc: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

I will reach you to chat more about how we can better handle your contribuitions.

**Comment by abobwhite** [comment]
Thanks @lpirola I just want to make sure this is going somewhere. I realize it's a tough balance managing open source projects with just a couple people and doing it all out of the goodness of your/our hearts and love for our work. But to be useful it's got to still be maintained. Which is why I offered those two options. Thanks for reaching. We'll make this work.

**Comment by abobwhite** [comment]
It looks like we're already behind again since slate is moving so fast. I can go ahead and move to the latest 0.27.x on this PR or we can do a follow-up from this one. Base on their changelog I don't expect much to change. Many just a line or two, if any.

**Comment by lpirola** [comment]
@abobwhite I tried to upgrade to latest version, but seems tests are broken. I will continue trying to fix tests because I want to release a new version today.

**Comment by abobwhite** [comment]
@lpirola Using my branch or another branch?

**Comment by lpirola** [comment]
@abobwhite using your branch.

**Comment by abobwhite** [comment]
Thanks for merging, @lpirola 

I hope this can be published to npm soon!

We can work on upgrading again to the "new" latest on a new PR.

**Pull request merged**
